/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50: "var(--brand-50)",
          100: "var(--brand-100)",
          200: "var(--brand-200)",
          300: "var(--brand-300)",
          400: "var(--brand-400)",
          500: "var(--brand-500)",
          600: "var(--brand-600)",
          700: "var(--brand-700)",
          800: "var(--brand-800)",
          900: "var(--brand-900)",
          950: "var(--brand-950)",
        },
        accent: {
          50: "var(--accent-50)",
          100: "var(--accent-100)",
          200: "var(--accent-200)",
          300: "var(--accent-300)",
          400: "var(--accent-400)",
          500: "var(--accent-500)",
          600: "var(--accent-600)",
          700: "var(--accent-700)",
          800: "var(--accent-800)",
          900: "var(--accent-900)",
          950: "var(--accent-950)",
        },
        surface: {
          50: "var(--surface-50)",
          100: "var(--surface-100)",
          200: "var(--surface-200)",
          300: "var(--surface-300)",
          400: "var(--surface-400)",
          500: "var(--surface-500)",
          600: "var(--surface-600)",
          700: "var(--surface-700)",
          800: "var(--surface-800)",
          900: "var(--surface-900)",
          950: "var(--surface-950)",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          subtle: "var(--color-primary-subtle)",
          text: "var(--color-primary-text)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          hover: "var(--color-secondary-hover)",
          text: "var(--color-secondary-text)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          light: "var(--success-light)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          light: "var(--error-light)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          light: "var(--warning-light)",
        },
        background: "var(--color-background)",
        foreground: "var(--color-text-primary)",
        card: "var(--color-surface)",
        "card-foreground": "var(--color-text-primary)",
        border: "var(--color-border)",
        muted: "var(--color-surface-hover)",
        "muted-foreground": "var(--color-text-muted)",
      },
      fontFamily: {
        heading: ["Raleway_700Bold", "Raleway_600SemiBold", "Raleway_400Regular", "sans-serif"],
        body: [
          "Nunito_400Regular",
          "Nunito_500Medium",
          "Nunito_600SemiBold",
          "Nunito_700Bold",
          "sans-serif",
        ],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "heading-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "heading-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      spacing: {
        18: "72px",
        22: "88px",
        30: "120px",
        34: "136px",
        42: "168px",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
    },
  },
  plugins: [],
};
