import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsString, IsOptional } from "class-validator";

export class UssdRequestDto {
  @ApiProperty({ description: "Unique session ID generated by mobile network operator" })
  @IsString()
  sessionId: string;

  @ApiProperty({ description: "USSD shortcode dialled (e.g. *920*26#)" })
  @IsString()
  serviceCode: string;

  @ApiProperty({ description: "Farmer phone number in international format (+233...)" })
  @IsString()
  phoneNumber: string;

  @ApiProperty({ description: "User navigation string separated by asterisk (*)" })
  @IsString()
  @IsOptional()
  text?: string;

  @ApiPropertyOptional({ description: "Network operator (MTN, Telecel, AirtelTigo)" })
  @IsString()
  @IsOptional()
  network?: string;
}

export class UssdResponseDto {
  @ApiProperty({
    description: "USSD response string prefixed with CON (continue) or END (terminate)",
  })
  message: string;
}
